name: Deploy Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Install dependencies
        working-directory: client
        run: |
          flutter pub get
          flutter create .
      - name: Build web
        working-directory: client
        run: flutter build web --release --base-href /UC4ERPG/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/build/web
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4